export default {
  light: {
    text: '#081269',
    background: '#ffffff',
    tint: '#081269',
    tabIconDefault: '#c7c9ff',
    tabIconSelected: '#081269',
    primary: '#081269',
    secondary: '#000c74',
    accent: '#c7c9ff',
    surface: '#ffffff',
    error: '#ff3b30',
    inputBackground: '#f0f2ff',
    border: '#c7c9ff',
    white: '#ffffff',
  },
  dark: {
    text: '#ffffff',
    background: '#ffffff',
    tint: '#c7c9ff',
    tabIconDefault: '#c7c9ff',
    tabIconSelected: '#081269',
    primary: '#081269',
    secondary: '#000c74',
    accent: '#c7c9ff',
    surface: '#ffffff',
    error: '#ff3b30',
    inputBackground: '#f0f2ff',
    border: '#c7c9ff',
    white: '#ffffff',
  },
};